<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use InvalidArgumentException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use BackendBundle\Entity\Commune;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserByNomPrenom($prenom, $nom)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb-> select('u')
           -> from('UserBundle:User', 'u')
           -> orderBy('u.prenom', 'ASC')
           -> where('u.prenom = :prenom')
           -> setParameter('prenom', $prenom)
           -> andWhere('u.nom = :nom')
           -> setParameter('nom', $nom)
           -> orderBy('u.nom', 'ASC');

        return $qb->getQuery()
                  ->getResult();
    }

    public function getUserByNomPrenomLike($prenom, $nom)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb-> select('u')
           -> from('UserBundle:User', 'u')
           -> orderBy('u.prenom', 'ASC')
           -> where($qb->expr()->like('u.prenom', ':prenom'))
           -> setParameter('prenom', '%'.$prenom.'%')
           -> andWhere($qb->expr()->like('u.nom', ':nom'))
           -> setParameter('nom', '%'.$nom.'%')
           -> orderBy('u.nom', 'ASC');

        return $qb->getQuery()
                  ->getResult();
    }
}
