homepage:
    path:       /
    defaults:   { _controller:AppBundle:Default:index }

check:
    path: /macif/check
    defaults:   { _controller:AppBundle:Default:check }

macif.user.check:
    path: /macif/userCheck
    methods: GET
    defaults: { _controller: AppBundle:Default:userCheck }
    options:
        expose: true
